---
timeout: 2
limit: 1024
targets:
  - name: "app1"
    ip: "127.0.0.1"
    workers: 1000
    tcp:
      period: "12h"
      range: "reserved"
      expected: "22,80,443"
    icmp:
      period: "1m"
