---
targets:
  - name: "laptop"
    ip: "192.168.42.228"
    workers: 10000
    tcp:
      period: "1m"
      range: "all"
      expected: "22,33,44"
    # udp:
    #   period: "1m"
    #   range: "1234"
    #   expected: "22,53"
    icmp:
      period: "30s"