---
targets:
  - name: "app.db"
    ip: "x.x.x.x"
    tcp:
      range: "all"
      expected: "22,33,44"
    udp:
      range: "1-1024"
      expected: "22,53"

  - name: "app.web"
    ip: "y.y.y.y"
    tcp:
      range: "all"
      expected: "22,33,44"
    udp:
      range: "1-1024"
      expected: "22,53"