---
targets:
  - name: "laptop"
    ip: "192.168.101.66"
    workers: 1000
    tcp:
      period: "30s"
      range: "all"
      expected: "6000"
    # udp:
    #   period: "20s"
    #   range: "all"
    #   expected: "22,53"
    icmp:
      period: "5s"