---
targets:
  - name: "laptop"
    ip: "192.168.42.229"
    tcp:
      period: "10s"
      range: "80,22222"
      expected: "22,33,44"
    udp:
      period: "20s"
      range: "all"
      expected: "22,53"
    icmp:
      period: "5s"