---
targets:
  - name: "mock"
    ip: "154.123.546.54"
    tcp:
      range: "all"
      expected: "22,33,44"
    udp:
      range: "1-1024"
      expected: "22,53"

  - name: "laptop"
    ip: "127.0.0.1"
    tcp:
      range: "all"
      expected: "22,33,44"
    udp:
      range: "1-1024"
      expected: "22,53"