---
targets:
  # - name: "blog"
  #   period: "1h"
  #   ip: "185.199.111.153"
  #   tcp:
  #     range: "reserved"
  #     expected: "22,33,44"
  #   udp:
  #     range: "1-1024"
  #     expected: "22,53"

  - name: "laptop"
    ip: "127.0.0.1"
    tcp:
      period: "1h"
      range: "all"
      expected: "22,33,44"
    udp:
      period: "2h"
      range: "1-1024"
      expected: "22,53"
    icmp:
      period: "10s"