---
timeout: 2
limit: 1024
log_level: "info"
targets:
  - name: "app1"
    ip: "127.0.0.1"
    tcp:
      period: "12h"
      range: "reserved"
      expected: "22,80,443"
    icmp:
      period: "1m"
