scanexporter:
    name: scan-exporter
    replicaCount: 1
    liveness:
        period: 3
        path: /health
    container:
        image: devopsworks/scan-exporter:0.6.2
        port: 2112

redis:
    name: redis
    usePassword: false
    replicaCount: 1
    db: 0
    container:
        image: redis:latest
        port: 6379

nameOverride: ""
fullnameOverride: ""

podMonitor: 
    enabled: false
    path: /metrics

targets: |-
         targets:       
             - name: "website"
               ip: "34.90.142.99"
               workers: 1000
               tcp:
                 period: "30s"
                 range: "all"
                 expected: "80,443"
               icmp:
                 period: "5s"
